name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

permissions: # ★ この行から追加 ★
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # HTML ファイルをビルドする（ビルド不要ならスキップしてOK）
      # 例：dist/ にコピーすると想定
      - name: Build HTML (optional)
        run: |
          mkdir -p dist
          cp -r html/* dist/

      # GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
